name: Release

on:
  push:
    tags:
      - 'v*'  # Match tags like v2025.03.28

jobs:
  release:
    name: Build & Upload Release
    runs-on: ubuntu-latest

    permissions:
      contents: write # Required to create release and upload assets

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Set VERSION from tag
        id: vars
        run: echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Build for release targets
        run: |
          mkdir -p dist

          platforms=(
            "linux amd64"
            "linux arm64"
            "darwin amd64"
            "darwin arm64"
          )

          for platform in "${platforms[@]}"; do
            set -- $platform
            GOOS=$1 GOARCH=$2 \
              go build \
                -ldflags="-s -w -X main.version=$VERSION" \
                -o dist/uit-$GOOS-$GOARCH \
                ./cmd/uit
          done

      - name: Compress binaries
        run: |
          mkdir -p dist/archives
          for f in dist/uit-*; do
            [ -f "$f" ] || continue  # Skip if no files matched
            name=$(basename "$f")
            platform=${name#uit-}
            mkdir -p dist/tmp/$platform
            cp "$f" dist/tmp/$platform/uit
            cp README.md dist/tmp/$platform/
            tar -czf dist/archives/uit-$platform.tar.gz -C dist/tmp/$platform uit README.md
          done

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          name: "Release ${{ env.VERSION }}"
          files: dist/archives/*.tar.gz


