name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Build & Upload Release
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Set VERSION from tag
        id: vars
        run: echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Build binaries
        run: |
          chmod +x scripts/build.sh
          ./scripts/build.sh uit dist $VERSION

      - name: Package binaries
        run: |
          chmod +x scripts/package.sh
          ./scripts/package.sh uit dist

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          name: "Release ${{ env.VERSION }}"
          files: dist/archives/*.tar.gz

